all:
	lualatex 43_handoff.tex
	bibtex 43_handoff
	lualatex 43_handoff.tex
	lualatex 43_handoff.tex
	rm 43_handoff.aux 43_handoff.bbl 43_handoff.blg 43_handoff.log 43_handoff.toc
clean:
	rm 43_handoff.pdf
