all:
	lualatex 43_designdocumentdraft1.tex
	rm 43_designdocumentdraft1.log 43_designdocumentdraft1.aux
	lualatex 43_designdocumentdraft2.tex
	rm 43_designdocumentdraft2.log 43_designdocumentdraft2.aux
draft1:
	lualatex 43_designdocumentdraft1.tex
	rm 43_designdocumentdraft1.log 43_designdocumentdraft1.aux
draft2:
	lualatex 43_designdocumentdraft2.tex
	rm 43_designdocumentdraft2.log 43_designdocumentdraft2.aux
clean:
	rm 43_designdocumentdraft1.toc 43_designdocumentdraft1.pdf
	rm 43_designdocumentdraft2.toc 43_designdocumentdraft2.pdf
