all:
	lualatex kollch_tech_review.tex
	bibtex kollch_tech_review.aux
	lualatex kollch_tech_review.tex
	lualatex kollch_tech_review.tex
	rm kollch_tech_review.log kollch_tech_review.aux kollch_tech_review.bbl kollch_tech_review.blg
clean:
	rm kollch_tech_review.pdf
